# Generated by Django 5.1.3 on 2024-12-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vendors_cover_image_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐ '), (5, '⭐⭐⭐⭐⭐'), (1, '⭐'), (2, '⭐⭐')], default=None),
        ),
    ]
