# Generated by Django 5.1.3 on 2024-12-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_cartorderitem_order_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mfd',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('disabled', 'Disabled')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[(4, '⭐⭐⭐⭐ '), (2, '⭐⭐'), (3, '⭐⭐⭐'), (1, '⭐'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
