# Generated by Django 5.1.3 on 2024-12-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_category_options_remove_product_digital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('in_review', 'In Review'), ('disabled', 'Disabled')], default='in_review', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
