# Generated by Django 5.1.3 on 2024-12-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'In Review'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published')], default='in_review', max_length=100),
        ),
    ]
