# Generated by Django 5.1.3 on 2024-12-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_product_options_product_digital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('5', '⭐⭐⭐⭐⭐'), ('3', '⭐⭐⭐☆☆'), ('2', '⭐⭐☆☆'), ('4', '⭐⭐⭐⭐☆'), ('1', '⭐☆☆☆☆')], default=None),
        ),
    ]
