# Generated by Django 5.1.3 on 2024-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('Processing', 'Processing'), ('delivered', 'Delivered')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.ImageField(upload_to='order_images/'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('Processing', 'Processing'), ('delivered', 'Delivered')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('draft', 'Draft'), ('in_review', 'In Review'), ('disabled', 'Disabled'), ('published', 'Published')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('2', '⭐⭐☆☆'), ('4', '⭐⭐⭐⭐☆'), ('3', '⭐⭐⭐☆☆'), ('5', '⭐⭐⭐⭐⭐'), ('1', '⭐☆☆☆☆')], default=None),
        ),
    ]
