# Generated by Django 5.1.3 on 2024-12-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'In Review')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('4', '⭐⭐⭐⭐☆'), ('2', '⭐⭐☆☆'), ('5', '⭐⭐⭐⭐⭐'), ('1', '⭐☆☆☆☆'), ('3', '⭐⭐⭐☆☆')], default=None),
        ),
    ]
