# Generated by Django 5.1.3 on 2024-12-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_address_contact_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('shipped', 'Shipped'), ('Processing', 'Processing')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('shipped', 'Shipped'), ('Processing', 'Processing')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('4', '⭐⭐⭐⭐☆'), ('2', '⭐⭐☆☆'), ('3', '⭐⭐⭐☆☆'), ('1', '⭐☆☆☆☆'), ('5', '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
