# Generated by Django 5.1.3 on 2024-12-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('Processing', 'Processing')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('delivered', 'Delivered'), ('Processing', 'Processing')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('3', '⭐⭐⭐☆☆'), ('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐☆'), ('2', '⭐⭐☆☆'), ('1', '⭐☆☆☆☆')], default=None),
        ),
    ]
