# Generated by Django 5.1.3 on 2024-12-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('Processing', 'Processing'), ('shipped', 'Shipped')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('Processing', 'Processing'), ('shipped', 'Shipped')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('disabled', 'Disabled'), ('draft', 'Draft'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('3', '⭐⭐⭐☆☆'), ('2', '⭐⭐☆☆'), ('1', '⭐☆☆☆☆'), ('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
