# Generated by Django 5.1.3 on 2024-12-23 17:03

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_product_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorder',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='sku', unique=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Processing', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published'), ('in_review', 'In Review'), ('disabled', 'Disabled')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('3', '⭐⭐⭐☆☆'), ('2', '⭐⭐☆☆'), ('1', '⭐☆☆☆☆'), ('5', '⭐⭐⭐⭐⭐'), ('4', '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
