# Generated by Django 5.1.3 on 2024-12-23 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_cartorder_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('draft', 'Draft'), ('published', 'Published')], default='in_review', max_length=100),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(choices=[('4', '⭐⭐⭐⭐☆'), ('5', '⭐⭐⭐⭐⭐'), ('1', '⭐☆☆☆☆'), ('2', '⭐⭐☆☆'), ('3', '⭐⭐⭐☆☆')], default=None),
        ),
    ]
